### ISSUE TITLE
Added in .gitignore the vendor directory

### ISSUE THREAD

**Issue by nunocodex** [pedroborges/kirby-blade-template#3]
I think you need to remove the vendor folder from repository and write to use `composer init` in the folder to install the vendor packages.

**Comment by pedroborges** [comment]
Your suggestion would be ideal, unfortunately Kirby itself hasn't fully adopted Composer. Right now this is best way to handle it to keep the plugin easy to install and use for the larger Kirby user base.

There have been some discussion on the community around this topic, [check it out](https://forum.getkirby.com/t/plugin-developers-convention-for-installation-via-composer/6626).
