### ISSUE TITLE
Saving old template data

### ISSUE THREAD

**Issue by nunocodex** [pedroborges/kirby-blade-template#4]
I see this https://github.com/pedroborges/kirby-blade-template/blob/master/src/Template.php#L94-L95 and I don't understand why this, can explain?

**Comment by pedroborges** [comment]
Kirby Blade component extends the default template component. This allows you to use Blade and plain PHP templates at the same time for things like plugin templates, for example.

So most of that code comes from Kirby's template component, see: https://github.com/getkirby/kirby/blob/master/kirby/component/template.php#L105-L106

I really don't know if Kirby uses this data after the template is rendered.
