### ISSUE TITLE
Echoing kirbytext with an ampersand converts to &amp;

### ISSUE THREAD

**Issue by syropian** [pedroborges/kirby-blade-template#6]
Something like `{{ $page->text()->kirbytext() }}` where the contents includes an `&` gets converted to `&amp;`. Any ways around this?

**Comment by pedroborges** [comment]
Hi @syropian, any expression inside double brackets are automatically sent through Kirby's `html` function. So in your case it's escaping the text twice. Use the syntax below instead for all `kirbytext` fields:

```blade
{!! $page->text()->kirbytext() !!}
```

_By the way, I'm doing some updates on this plugin to display better error messages on the Whoops page and upgrade it to the latest Blade version. Check back by the end of the week._

**Comment by syropian** [comment]
Great! Thanks Pedro 🙏
