### ISSUE TITLE
Kirby 3

### ISSUE THREAD

**Issue by obelmont** [pedroborges/kirby-blade-template#8]
Just curious to know if this works with Kirby 3?
I haven't had the opportunity to use it (v3) yet and don't think I would be able to go back to pre blade Kirby!

**Comment by pedroborges** [comment]
I can't live without Blade as well.

I have a working version I used on a Kirby 3 project a while ago. I'll try to polish it and publish here until next week.

**Comment by francisceril** [comment]
Can't wait for it either.

**Comment by pedroborges** [comment]
Checkout the update I just pushed to the master branch. Docs will be updated soon.
