### ISSUE TITLE
Fatal error: Cannot redeclare e()

### ISSUE THREAD

**Issue by weeg** [pedroborges/kirby-blade-template#9]
After installing kirby-blade-template the CMS did not start to work.

Kirby and Laravel have an e() helper function and Kirby cannot redeclare it.

As a workaround I was extending the index.php to look like this. I don't know if there is any other workaround.
```php
require __DIR__ . '/kirby/config/helpers.php';
require __DIR__ . '/kirby/bootstrap.php';

echo (new Kirby)->render();
```

**Comment by pedroborges** [comment]
Checkout the update I just pushed to the master branch. Docs will be updated soon.
